#!/bin/bash


# 打包依赖jar命令，需要安装java并配置环境变量

current_path=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

# 判断打包目录是否存在
target=$current_path/target/

parcels(){
	if [ ! -d $target ];then
 		 mkdir $target
	fi

	# succeeded.
	status=`java -jar $current_path/lib/validator.jar -s $current_path/descriptor/service.sdl | awk 'END{if($2 ~ "succeeded") {print 0} else print -1 }'`

	#echo $status
	if [ x"$status" == x"0" ];then
		if [ -d $current_path/_aux/ ];then
        		mv $current_path/_aux/ $current_path/aux/
	        fi
		cd $current_path
        	echo `jar -cvf $current_path/target/ELASTICSEARCH-7.9.0.jar aux/ descriptor/ images/ scripts/`
	else
        	echo `java -jar $current_path/lib/validator.jar -s $current_path/descriptor/service.sdl`
	fi

}

clean(){
	# 判断打包目录是否存在
	if [ -d $target ];then
        	rm -r $target
        fi
}

case "$1" in
    package)
        parcels
        ;;
    clean)
	clean
	;;
    *)
        echo "Usage building parcels {package|clean}"
        ;;
esac
